-- settings
require "user.options"
require "user.keymaps"
require "user.plugins"
-- require "user.impatient"
require "user.colorscheme"
-- code completion, diagnosticsq
require "user.cmp"
require "user.lsp"
-- other plugins
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.gitsigns"
require "user.nvim-tree"
require "user.bufferline"
require "user.lualine"
require "user.toggleterm"
require "user.project"
require "user.indentline"
require "user.alpha"
require "user.whichkey"
require "user.numb"
require "user.dial"
require "user.colorizer"
require "user.spectre"
require "user.zen"
require "user.neoscroll"
require "user.todo"
require "user.surround"
require "user.notify"
-- debugging, languages
require "user.dapui"
require "user.rust"
